In [8]:
import numpy as np 
import pandas as pd
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori

In [9]:
store_data = pd.read_csv('store_data.csv',header=None)  
store_data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
#To convert our pandas dataframe into a list of lists, execute the following script:

records = []  
for i in range(0, 7501):  
    records.append([str(store_data.values[i,j]) for j in range(0, 20)])

In [11]:
records[0]

['shrimp',
 'almonds',
 'avocado',
 'vegetables mix',
 'green grapes',
 'whole weat flour',
 'yams',
 'cottage cheese',
 'energy drink',
 'tomato juice',
 'low fat yogurt',
 'green tea',
 'honey',
 'salad',
 'mineral water',
 'salmon',
 'antioxydant juice',
 'frozen smoothie',
 'spinach',
 'olive oil']

In [12]:

te = TransactionEncoder()
te_ary = te.fit(records).transform(records)
print(te_ary)

[[False  True  True ...  True False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False  True False]]

In [13]:
df = pd.DataFrame(te_ary, columns=te.columns_)
print(df)

       asparagus  almonds  antioxydant juice  asparagus  avocado  babies food  \
0          False     True               True      False     True        False
1          False    False              False      False    False        False
2          False    False              False      False    False        False
3          False    False              False      False     True        False
4          False    False              False      False    False        False
5          False    False              False      False    False        False
6          False    False              False      False    False        False
7          False    False              False      False    False        False
8          False    False              False      False    False        False
9          False    False              False      False    False        False
10         False    False              False      False    False        False
11         False    False              False      False    False        False
12         False    False              False      False    False        False
13         False    False              False      False    False        False
14         False    False              False      False    False        False
15         False    False              False      False    False        False
16         False    False              False      False    False        False
17         False    False              False      False    False        False
18         False    False              False      False    False        False
19         False    False              False      False    False        False
20         False    False              False      False    False        False
21         False    False              False      False    False        False
22         False    False              False      False    False        False
23         False    False              False      False     True        False
24         False    False              False      False    False        False
25         False    False              False      False     True        False
26         False    False              False      False    False        False
27         False    False              False      False    False        False
28         False    False              False      False    False        False
29         False    False              False      False    False        False
...          ...      ...                ...        ...      ...          ...
7471       False    False              False      False    False        False
7472       False    False              False      False    False        False
7473       False    False              False      False    False        False
7474       False    False              False      False    False        False
7475       False    False              False      False    False        False
7476       False    False              False      False    False        False
7477       False    False              False      False    False        False
7478       False    False              False      False    False        False
7479       False    False              False      False    False        False
7480       False    False              False      False    False        False
7481       False    False              False      False    False        False
7482       False    False              False      False    False        False
7483       False    False              False      False    False        False
7484       False    False              False      False    False        False
7485       False    False              False      False    False        False
7486       False    False              False       True    False        False
7487       False    False              False      False    False        False
7488       False    False              False      False    False        False
7489       False    False              False      False    False        False
7490       False    False              False      False    False        False
7491       False    False              False      False    False        False
7492       False    False              False      False    False        False
7493       False    False              False      False    False        False
7494       False    False              False      False    False        False
7495       False    False              False      False    False        False
7496       False    False              False      False    False        False
7497       False    False              False      False    False        False
7498       False    False              False      False    False        False
7499       False    False              False      False    False        False
7500       False    False              False      False    False        False

      bacon  barbecue sauce  black tea  blueberries    ...     turkey  \
0     False           False      False        False    ...      False
1     False           False      False        False    ...      False
2     False           False      False        False    ...      False
3     False           False      False        False    ...       True
4     False           False      False        False    ...      False
5     False           False      False        False    ...      False
6     False           False      False        False    ...      False
7     False           False      False        False    ...      False
8     False           False      False        False    ...      False
9     False           False      False        False    ...      False
10    False           False      False        False    ...      False
11    False           False      False        False    ...      False
12    False           False      False        False    ...       True
13    False           False      False        False    ...      False
14    False           False      False        False    ...      False
15    False           False      False        False    ...      False
16    False           False      False        False    ...      False
17    False           False      False        False    ...       True
18    False           False       True        False    ...       True
19    False           False      False        False    ...      False
20    False           False      False        False    ...      False
21    False           False      False        False    ...      False
22    False           False      False        False    ...      False
23    False           False      False        False    ...      False
24    False           False      False        False    ...      False
25    False           False      False        False    ...      False
26    False           False       True        False    ...      False
27    False           False      False        False    ...      False
28    False           False      False        False    ...      False
29    False           False      False        False    ...      False
...     ...             ...        ...          ...    ...        ...
7471  False           False      False        False    ...      False
7472  False           False      False        False    ...      False
7473  False           False      False        False    ...      False
7474  False           False      False        False    ...       True
7475  False           False      False        False    ...       True
7476  False           False      False        False    ...      False
7477  False           False      False        False    ...      False
7478  False           False      False        False    ...       True
7479  False           False      False        False    ...      False
7480  False           False      False        False    ...      False
7481  False           False      False        False    ...      False
7482  False           False      False        False    ...      False
7483  False           False      False        False    ...      False
7484  False           False      False        False    ...      False
7485  False           False      False        False    ...      False
7486  False           False      False        False    ...      False
7487  False           False      False        False    ...      False
7488  False           False      False        False    ...      False
7489  False           False      False        False    ...      False
7490  False           False      False        False    ...      False
7491  False           False      False        False    ...      False
7492  False           False      False        False    ...      False
7493  False           False      False        False    ...      False
7494  False           False      False        False    ...       True
7495  False           False      False        False    ...      False
7496  False           False      False        False    ...      False
7497  False           False      False        False    ...      False
7498  False           False      False        False    ...      False
7499  False           False      False        False    ...      False
7500  False           False      False        False    ...      False

      vegetables mix  water spray  white wine  whole weat flour  \
0               True        False       False              True
1              False        False       False             False
2              False        False       False             False
3              False        False       False             False
4              False        False       False             False
5              False        False       False             False
6              False        False       False             False
7              False        False       False             False
8              False        False       False             False
9              False        False       False             False
10             False        False       False             False
11             False        False       False             False
12             False        False       False             False
13             False        False       False             False
14             False        False       False             False
15             False        False       False             False
16             False        False       False             False
17             False        False       False             False
18             False        False       False             False
19             False        False       False             False
20             False        False       False             False
21             False        False       False             False
22             False        False       False             False
23             False        False        True             False
24             False        False       False             False
25             False        False       False             False
26             False        False       False             False
27             False        False       False             False
28             False        False       False             False
29             False        False       False             False
...              ...          ...         ...               ...
7471           False        False       False             False
7472           False        False       False             False
7473           False        False       False             False
7474            True        False       False             False
7475           False        False       False             False
7476           False        False       False             False
7477           False        False       False             False
7478           False        False       False             False
7479           False        False       False             False
7480           False        False       False             False
7481           False        False       False             False
7482           False        False       False             False
7483           False        False       False             False
7484           False        False       False             False
7485           False        False        True             False
7486           False        False       False             False
7487           False        False       False             False
7488           False        False       False             False
7489           False        False       False             False
7490           False        False       False             False
7491           False        False       False             False
7492           False        False       False             False
7493           False        False       False             False
7494           False        False       False             False
7495           False        False       False             False
7496           False        False       False             False
7497           False        False       False             False
7498           False        False       False             False
7499           False        False       False             False
7500           False        False       False             False

      whole wheat pasta  whole wheat rice   yams  yogurt cake  zucchini
0                 False             False   True        False     False
1                 False             False  False        False     False
2                 False             False  False        False     False
3                 False             False  False        False     False
4                 False              True  False        False     False
5                 False             False  False        False     False
6                  True             False  False        False     False
7                 False             False  False        False     False
8                 False             False  False        False     False
9                 False             False  False        False     False
10                False             False  False        False     False
11                False             False  False        False     False
12                False             False  False        False     False
13                False             False  False        False     False
14                False             False  False        False     False
15                False             False  False        False     False
16                False             False  False        False     False
17                False             False  False        False     False
18                False             False  False        False     False
19                False             False  False        False     False
20                False             False  False        False     False
21                False             False  False        False     False
22                False             False  False        False     False
23                False             False  False        False     False
24                False             False  False        False     False
25                False             False  False        False     False
26                False             False  False        False     False
27                False             False  False        False     False
28                False             False  False        False     False
29                False             False   True        False     False
...                 ...               ...    ...          ...       ...
7471              False             False  False        False     False
7472              False             False  False        False     False
7473              False              True  False        False     False
7474              False             False  False        False     False
7475              False             False  False        False     False
7476              False             False  False        False     False
7477              False             False  False        False     False
7478              False              True  False        False     False
7479              False             False  False        False     False
7480              False             False  False        False     False
7481              False             False  False        False     False
7482              False             False  False        False     False
7483               True             False  False        False     False
7484              False             False  False        False     False
7485              False             False  False        False     False
7486              False             False  False        False     False
7487              False             False  False        False     False
7488              False              True  False        False     False
7489              False             False  False        False     False
7490              False             False  False        False     False
7491              False             False  False        False     False
7492              False             False  False        False     False
7493              False             False  False        False     False
7494              False              True  False        False     False
7495              False             False  False        False     False
7496              False             False  False        False     False
7497              False             False  False        False     False
7498              False             False  False        False     False
7499              False             False  False        False     False
7500              False             False  False         True     False

[7501 rows x 121 columns]

In [22]:
frequent_itemsets = apriori(df, min_support=0.0045, use_colnames=True)

print (frequent_itemsets)

       support                                           itemsets
0     0.020397                                          (almonds)
1     0.008932                                (antioxydant juice)
2     0.004666                                        (asparagus)
3     0.033329                                          (avocado)
4     0.004533                                      (babies food)
5     0.008666                                            (bacon)
6     0.010799                                   (barbecue sauce)
7     0.014265                                        (black tea)
8     0.009199                                      (blueberries)
9     0.011465                                       (body spray)
10    0.033729                                         (brownies)
11    0.008666                                        (bug spray)
12    0.005866                                     (burger sauce)
13    0.087188                                          (burgers)
14    0.030129                                           (butter)
15    0.081056                                             (cake)
16    0.009732                                       (candy bars)
17    0.015331                                          (carrots)
18    0.004799                                      (cauliflower)
19    0.025730                                          (cereals)
20    0.046794                                        (champagne)
21    0.059992                                          (chicken)
22    0.006133                                            (chili)
23    0.163845                                        (chocolate)
24    0.010532                                            (cider)
25    0.008399                              (clothes accessories)
26    0.080389                                          (cookies)
27    0.051060                                      (cooking oil)
28    0.004799                                             (corn)
29    0.031862                                   (cottage cheese)
...        ...                                                ...
1654  0.008532              (mineral water, nan, olive oil, milk)
1655  0.007866               (milk, mineral water, nan, pancakes)
1656  0.007866                 (mineral water, nan, shrimp, milk)
1657  0.008532                   (mineral water, nan, soup, milk)
1658  0.015731              (mineral water, spaghetti, nan, milk)
1659  0.006532               (tomatoes, mineral water, nan, milk)
1660  0.006133                 (mineral water, turkey, nan, milk)
1661  0.005066       (whole wheat rice, mineral water, nan, milk)
1662  0.007199                  (spaghetti, nan, olive oil, milk)
1663  0.004933                   (milk, spaghetti, nan, pancakes)
1664  0.004933                     (spaghetti, nan, shrimp, milk)
1665  0.004533                       (spaghetti, nan, soup, milk)
1666  0.005866                   (tomatoes, spaghetti, nan, milk)
1667  0.004799                     (spaghetti, turkey, nan, milk)
1668  0.004666          (mineral water, nan, olive oil, pancakes)
1669  0.005199              (mineral water, nan, olive oil, soup)
1670  0.010265         (mineral water, nan, spaghetti, olive oil)
1671  0.004533             (mineral water, nan, shrimp, pancakes)
1672  0.011465          (mineral water, spaghetti, nan, pancakes)
1673  0.004666           (tomatoes, mineral water, nan, pancakes)
1674  0.006799            (mineral water, nan, spaghetti, salmon)
1675  0.008532            (mineral water, spaghetti, shrimp, nan)
1676  0.007466              (mineral water, nan, spaghetti, soup)
1677  0.009332          (tomatoes, mineral water, spaghetti, nan)
1678  0.006399            (turkey, mineral water, spaghetti, nan)
1679  0.006266  (whole wheat rice, mineral water, spaghetti, nan)
1680  0.005066              (spaghetti, nan, olive oil, pancakes)
1681  0.004533   (spaghetti, chocolate, mineral water, nan, eggs)
1682  0.004933   (spaghetti, chocolate, milk, mineral water, nan)
1683  0.004533  (spaghetti, milk, frozen vegetables, mineral w...

[1684 rows x 2 columns]

In [23]:
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))

print (frequent_itemsets)

       support                                           itemsets  length
0     0.020397                                          (almonds)       1
1     0.008932                                (antioxydant juice)       1
2     0.004666                                        (asparagus)       1
3     0.033329                                          (avocado)       1
4     0.004533                                      (babies food)       1
5     0.008666                                            (bacon)       1
6     0.010799                                   (barbecue sauce)       1
7     0.014265                                        (black tea)       1
8     0.009199                                      (blueberries)       1
9     0.011465                                       (body spray)       1
10    0.033729                                         (brownies)       1
11    0.008666                                        (bug spray)       1
12    0.005866                                     (burger sauce)       1
13    0.087188                                          (burgers)       1
14    0.030129                                           (butter)       1
15    0.081056                                             (cake)       1
16    0.009732                                       (candy bars)       1
17    0.015331                                          (carrots)       1
18    0.004799                                      (cauliflower)       1
19    0.025730                                          (cereals)       1
20    0.046794                                        (champagne)       1
21    0.059992                                          (chicken)       1
22    0.006133                                            (chili)       1
23    0.163845                                        (chocolate)       1
24    0.010532                                            (cider)       1
25    0.008399                              (clothes accessories)       1
26    0.080389                                          (cookies)       1
27    0.051060                                      (cooking oil)       1
28    0.004799                                             (corn)       1
29    0.031862                                   (cottage cheese)       1
...        ...                                                ...     ...
1654  0.008532              (mineral water, nan, olive oil, milk)       4
1655  0.007866               (milk, mineral water, nan, pancakes)       4
1656  0.007866                 (mineral water, nan, shrimp, milk)       4
1657  0.008532                   (mineral water, nan, soup, milk)       4
1658  0.015731              (mineral water, spaghetti, nan, milk)       4
1659  0.006532               (tomatoes, mineral water, nan, milk)       4
1660  0.006133                 (mineral water, turkey, nan, milk)       4
1661  0.005066       (whole wheat rice, mineral water, nan, milk)       4
1662  0.007199                  (spaghetti, nan, olive oil, milk)       4
1663  0.004933                   (milk, spaghetti, nan, pancakes)       4
1664  0.004933                     (spaghetti, nan, shrimp, milk)       4
1665  0.004533                       (spaghetti, nan, soup, milk)       4
1666  0.005866                   (tomatoes, spaghetti, nan, milk)       4
1667  0.004799                     (spaghetti, turkey, nan, milk)       4
1668  0.004666          (mineral water, nan, olive oil, pancakes)       4
1669  0.005199              (mineral water, nan, olive oil, soup)       4
1670  0.010265         (mineral water, nan, spaghetti, olive oil)       4
1671  0.004533             (mineral water, nan, shrimp, pancakes)       4
1672  0.011465          (mineral water, spaghetti, nan, pancakes)       4
1673  0.004666           (tomatoes, mineral water, nan, pancakes)       4
1674  0.006799            (mineral water, nan, spaghetti, salmon)       4
1675  0.008532            (mineral water, spaghetti, shrimp, nan)       4
1676  0.007466              (mineral water, nan, spaghetti, soup)       4
1677  0.009332          (tomatoes, mineral water, spaghetti, nan)       4
1678  0.006399            (turkey, mineral water, spaghetti, nan)       4
1679  0.006266  (whole wheat rice, mineral water, spaghetti, nan)       4
1680  0.005066              (spaghetti, nan, olive oil, pancakes)       4
1681  0.004533   (spaghetti, chocolate, mineral water, nan, eggs)       5
1682  0.004933   (spaghetti, chocolate, milk, mineral water, nan)       5
1683  0.004533  (spaghetti, milk, frozen vegetables, mineral w...       5

[1684 rows x 3 columns]

In [25]:
frequent_itemsets[ (frequent_itemsets['length'] == 5) &
                   (frequent_itemsets['support'] >= 0.0045) ]

       support                                           itemsets  length
1681  0.004533   (spaghetti, chocolate, mineral water, nan, eggs)       5
1682  0.004933   (spaghetti, chocolate, milk, mineral water, nan)       5
1683  0.004533  (spaghetti, milk, frozen vegetables, mineral w...       5